//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIcomputers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ISBN { get; set; }
        public string title { get; set; }
        public Nullable<int> publishedYear { get; set; }
        public Nullable<int> borrower { get; set; }
        public int author { get; set; }
    
        public virtual Author Author1 { get; set; }
        public virtual Borrower Borrower1 { get; set; }
    }
}
